apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-sts
  namespace: default
spec:
  replicas: 1
  serviceName: ""
  selector:
    matchLabels:
      openebs.io/app: busybox-sts
  template:
    metadata:
      labels:
        openebs.io/app: busybox-sts
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                openebs.io/app: busybox-sts
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - sh
        - -c
        - 'date > /mnt/store1/date.txt; hostname >> /mnt/store1/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;'
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox-sts
        volumeMounts:
        - mountPath: /mnt/store1
          name: vol1
  volumeClaimTemplates:
  - metadata:
      name: vol1
      annotations:
        cas.openebs.io/config: |
          - name: BasePath
            value: "/var/openebs"
          - name: RelativePath
            value: "busybox-sts"
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: hostpath
      resources:
        requests:
          storage: 4G
