apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hp-abs
  annotations:
    cas.openebs.io/config: |
      - name: BasePath
        value: "/var/openebs"
      - name: RelativePath
        value: "busybox-rel"
      - name: AbsolutePath
        value: "/var/openebs/busybox-abs"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-abs
  namespace: default
spec:
  containers:
  - command:
       - sh
       - -c
       - 'date > /mnt/store1/date.txt; hostname >> /mnt/store1/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/store1
      name: demo-vol1
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: pvc-hp-abs
---
